import tkinter as tk
def saludar():
 nombre = entrada_nombre.get()
 edad = entrada_edad.get()
 etiqueta_resultado.config(text=f"Hola {nombre}, tienes{edad} años")
ventana = tk.Tk()
ventana.title("Mi primera app grafica")
ventana.geometry("600x250")
ventana.config(bg="#ffd6e0")
etiqueta_nombre = tk.Label(ventana, text="Ingresa tu nombre:")
etiqueta_nombre.pack()
entrada_nombre = tk.Entry(ventana)
entrada_nombre.pack()
etiqueta_edad = tk.Entry(ventana, text="Ingresa tu edad:")
entrada_edad.pack()
entrada_edad = tk.Entry(ventana)
entrada_edad.pack()
boton = tk.Button(ventana, text="Mostrar saludo", command=saludar)
boton.pack()
etiqueta_resultado = tk.Label(ventana, text="")
etiqueta_resultado.pack()
etiqueta_autor = tk.Label(ventana, text="Autor: Alejandra Maricel Romero Grande")
etiqueta_autor.pack()
ventana.mainloop()
